feat: auto detect css module based filename
onigoetz/postcss-lightningcss pull request #58
Opened 2023-03-30 07:41 UTC by JiangWeixian

2023-04-01 08:25 UTC, onigoetz requested changes
Hi, thanks for the PR!

I've added a comment on the name of the option; what do you think of my proposition?

2023-04-01 08:25 UTC, onigoetz commented on README.md
> +  cssModulesRe: /\.module\.css/,
I have the feeling this option should be renamed to `cssModules` and support the following options: 
- boolean:  as it supports today
- `"auto"`: uses the `/\.module\.\w+$/i` regex to decide
- `RegEx`: uses a custom RegEx

With the default being `false` to introduce no breaking change

Can you please make this change ?

2023-04-03 02:29 UTC, JiangWeixian commented on README.md
> +  cssModulesRe: /\.module\.css/,
Sure!

2023-04-06 20:41 UTC, merged

2023-04-06 21:44 UTC, onigoetz commented
This is released in 0.7.0 : https://github.com/onigoetz/postcss-lightningcss/releases/tag/0.7.0

thanks again for the contribution :)